version: '3.0'

services:
  app:
    image: 'simonesestito/wasaphoto:latest'
    build: .
    ports:
      - '${DOCKER_HOST_PROXY_PORT:-3000}:3000'
    environment:
      - 'CFG_LOG_DEBUG=false'
    volumes:
      - 'database:/app/db'
      - 'photos:/app/static/user_content'

volumes:
  database:
  photos:
